import type { ZodType } from "zod";
import {
  AnomalySchema,
  AppSettingsSchema,
  SeedResultSchema,
  TeamMetricsSchema,
  TeamSchema,
  TeamSummarySchema,
  type Anomaly,
  type AnomalySeverity,
  type AppSettings,
  type SeedResult,
  type Team,
  type TeamMetrics,
  type TeamSummary,
} from "@/lib/types";
import { z } from "zod";

/**
 * Typed client for the Watchtower FastAPI backend.
 *
 * Every response is re-validated with the same zod schemas the UI renders
 * from, so a backend field rename fails loudly here instead of silently
 * rendering `undefined` three components deep.
 */

/**
 * The deployed demo has no FastAPI backend to talk to, so it points at the
 * bundled snapshot routes instead (see app/api/demo). Everything else about
 * the client is identical, including the zod validation.
 */
export const IS_HOSTED_DEMO = process.env.NEXT_PUBLIC_DEMO_MODE === "1";

export const API_BASE_URL = IS_HOSTED_DEMO
  ? "/api/demo"
  : (process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000").replace(
      /\/$/,
      "",
    );

export class ApiError extends Error {
  readonly status: number;

  constructor(status: number, message: string) {
    super(message);
    this.name = "ApiError";
    this.status = status;
  }
}

async function request<T>(
  path: string,
  schema: ZodType<T>,
  init?: RequestInit,
): Promise<T> {
  let response: Response;
  try {
    response = await fetch(`${API_BASE_URL}${path}`, {
      ...init,
      headers: { Accept: "application/json", ...init?.headers },
    });
  } catch {
    // A dead backend is the single most likely failure in local development,
    // so it gets a message that says what to start rather than "fetch failed".
    throw new ApiError(0, `Cannot reach the Watchtower API at ${API_BASE_URL}`);
  }

  if (!response.ok) {
    throw new ApiError(response.status, await readErrorDetail(response));
  }

  return schema.parse(await response.json());
}

async function readErrorDetail(response: Response): Promise<string> {
  try {
    const body = await response.json();
    if (body && typeof body.detail === "string") return body.detail;
  } catch {
    // Non-JSON error body; fall through to the status text.
  }
  return `${response.status} ${response.statusText}`;
}

// --- reads -----------------------------------------------------------------

export function getTeams(): Promise<Team[]> {
  return request("/teams", z.array(TeamSchema));
}

export function getTeam(teamId: string): Promise<Team> {
  return request(`/teams/${teamId}`, TeamSchema);
}

export function getTeamMetrics(teamId: string): Promise<TeamMetrics> {
  return request(`/teams/${teamId}/metrics`, TeamMetricsSchema);
}

export function getTeamAnomalies(teamId: string): Promise<Anomaly[]> {
  return request(`/teams/${teamId}/anomalies`, z.array(AnomalySchema));
}

export function getAnomalies(severity?: AnomalySeverity): Promise<Anomaly[]> {
  const query = severity ? `?severity=${severity}` : "";
  return request(`/anomalies${query}`, z.array(AnomalySchema));
}

/**
 * The Phi-4 verdict is generated by a scheduled pass, so "not generated yet"
 * is an ordinary state rather than an error: the summary card renders an
 * explanation instead of the page falling over.
 */
export async function getTeamSummary(
  teamId: string,
): Promise<TeamSummary | null> {
  try {
    return await request(`/teams/${teamId}/summary`, TeamSummarySchema);
  } catch (error) {
    if (error instanceof ApiError && error.status === 404) return null;
    throw error;
  }
}

// --- streaming ask ---------------------------------------------------------

export interface AskOptions {
  signal?: AbortSignal;
  onToken?: (chunk: string) => void;
}

/**
 * Ask Phi-4 about one team and surface tokens as they arrive.
 *
 * The endpoint streams plain text, so the reader decodes incrementally with a
 * streaming TextDecoder: multi-byte characters can straddle a chunk boundary
 * and decoding each chunk in isolation would corrupt them.
 */
export async function askTeam(
  teamId: string,
  question: string,
  { signal, onToken }: AskOptions = {},
): Promise<string> {
  const response = await fetch(`${API_BASE_URL}/teams/${teamId}/ask`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ question }),
    signal,
  });

  if (!response.ok) {
    throw new ApiError(response.status, await readErrorDetail(response));
  }
  if (!response.body) {
    const text = await response.text();
    onToken?.(text);
    return text;
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let answer = "";

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    const chunk = decoder.decode(value, { stream: true });
    if (chunk) {
      answer += chunk;
      onToken?.(chunk);
    }
  }

  const tail = decoder.decode();
  if (tail) {
    answer += tail;
    onToken?.(tail);
  }

  return answer;
}

// --- writes ----------------------------------------------------------------

export async function refreshNow(): Promise<void> {
  const response = await fetch(`${API_BASE_URL}/admin/refresh`, {
    method: "POST",
  });
  if (!response.ok) {
    throw new ApiError(response.status, await readErrorDetail(response));
  }
}

// --- settings and demo data -------------------------------------------------

export function getSettings(): Promise<AppSettings> {
  return request("/admin/settings", AppSettingsSchema);
}

export function updateSettings(
  patch: Partial<Pick<AppSettings, "dataSource" | "githubRepos">>,
): Promise<AppSettings> {
  return request("/admin/settings", AppSettingsSchema, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(patch),
  });
}

/** Fill every table with the fabricated three-team organisation. */
export function seedDemoData(): Promise<SeedResult> {
  return request("/admin/seed-demo", SeedResultSchema, { method: "POST" });
}

/** Empty every data table, leaving configuration in place. */
export function clearAllData(): Promise<AppSettings> {
  return request("/admin/clear", AppSettingsSchema, { method: "POST" });
}
